### PR TITLE
Migrate from submodule to plugin using composer

### PR DESCRIPTION
**Pull request by nathanielks**
Added composer.json. Removed predis submodule in favor of composer.json dependency. On plugin activation, it'll move the object-cache.php file into the content directory. Once activated, it'll detect if the file is present. If not, it'll prompt to copy the plugin's copy to the directory. If one already exists, it'll prompt that it exists and give the option to overwrite it. On deactivation, the plugin will remove the file if no modifications have been made. This way, in case someone installs a new plugin that replaces the file, it won't remove that file.

I also added a few try/catch blocks in the cache-functions.php file. This way, if the redis server is not running, or not present, it won't throw a fatal error and crash the site. Instead, it'll report the error to the admin dashboard.

Added cache-functions.php file detection to object-cache.php, in case the plugin is moved or renamed and the object-cache.php file remains in place

### CODE REVIEW

**Comment by franz-josef-kaiser** [comment]
@ericmann So neither one ever happened?

**Comment by ericmann** [comment]
> So neither one ever happened?

Not yet. Closing for now. Can revisit later.

**Comment by franz-josef-kaiser** [comment]
@ericmann Why don't you leave PRs open until they are implemented or can get closed as duplicate/in-favor-of-X?

**Comment by ericmann** [comment]
No activity in over a year. Cleaning up my GH projects. Can always revisit later if there's interest and/or activity.

**Pull request closed without merging**
